  ---
title: "heatMapDashboard"
author: "Han Jiaxu"
date: '2022-10-21'
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(plotly)
library(jsonlite)
library(DT)
library(jsonlite)
##add fake information here first
data = readLines("fakeData.json")
fake_json = lapply(data, fromJSON)
data = data.frame(id = numeric(0), camera = numeric(0), time = character(0))
empty_table = data.frame()
for (i in 1:length(fake_json)) {
  idx = i
  occ = fake_json[[i]]$occurrence
  temp  = data.frame(id = idx, camera = occ[1], time = occ[2])
  data = rbind(data, temp)
  }
```

# Page 1

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r echo=FALSE}
data %>% filter(camera == 2) %>% select(-id) %>% 
  separate(time, c("day", "time"), sep = "-T") %>% mutate(time = str_sub(time, 1,nchar(time)-5)) %>%
  mutate_all(as.factor) %>% 
  select(-day) %>% group_by(time) %>% plot()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r echo=FALSE}
#plot(pressure)

```

### Chart C

```{r}
#plot(cars)
```


# Page 2


Column {data-width=250}
-------------------------------------
    
This is a different page, as indicated on the navigation bar above.
   
Column {.tabset, data-width=750}
-------------------------------------
   
### Plotly chart

```{r echo=FALSE}

```   
 
### Chart 3
    
```{r}

```
